
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

MOVE_DISTANCE = 10


RIGHT = 0
UP = 90
LEFT = 180
DOWN = 270

PA_MARGIN_X = 5
PA_MARGIN_Y = 50

PA_TOP_LEFT = ((SCREEN_WIDTH / 2) * -1 + PA_MARGIN_X, (SCREEN_HEIGHT / 2) -PA_MARGIN_Y)
PA_BOTTOM_LEFT = ((SCREEN_WIDTH / 2) * -1 + PA_MARGIN_X, (SCREEN_HEIGHT/2) * -1  +PA_MARGIN_Y)
PA_BOTTOM_RIGHT = (SCREEN_WIDTH /2 - PA_MARGIN_X - 5, (SCREEN_HEIGHT/2) * -1 +PA_MARGIN_Y)
PA_TOP_RIGHT = ((SCREEN_WIDTH/2)  - PA_MARGIN_X - 5, (SCREEN_HEIGHT / 2) -PA_MARGIN_Y)